name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify your Python version here

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: templates  # Change this to your templates directory

      - name: Build the site
        run: |
          # Add any build commands here (e.g., static site generator commands)
        working-directory: templates  # Change this to your templates directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: templates  # Change this to your templates directory
